### ISSUE TITLE
JavaScript 正则提取字符串

### ISSUE THREAD

**Issue by bingoogolapple** [bingoogolapple/bingoogolapple.github.io#166]
```JavaScript
let str = 'abcdefgname="test"sddfhskshjsfsjdfps'
        let reg = /name="((\w|-|\s)+)/ig
        str.replace(reg, function() {
          console.log(arguments)
          console.log(arguments.length)
          console.log(arguments[1])
        })

        console.log('\n---------------------------\n')

        str = 'url(http://localhost:8080/%E4%B8%AD%E7%A7%8B…4%BB%E5%8A%A8/banner.jpg)；'
        let aar = /url\((.+)\)/.exec(str)
        console.log(aar)
        aar = /url\((\S+)\)/.exec(str)
        console.log(aar)

        console.log('\n---------------------------\n')

        str = 'TypeError: Cannot read property \'length\' of undefined\n    at o.submit (http://localhost:18080/static/js/13.d54f45b1cc087699157a.js:1:3641)\n    at o.n [as submit] (http://localhost:18080/static/js/vendor.9393104e7831a4c3874e.js:6:664)\n    at click (http://localhost:18080/static/js/13.d54f45b1cc087699157a.js:1:5886)\n    at o.t (http://localhost:18080/static/js/vendor.9393104e7831a4c3874e.js:6:5222)\n    at o.e.$emit (http://localhost:18080/static/js/vendor.9393104e7831a4c3874e.js:6:56660)\n    at o.handleClick (http://localhost:18080/static/js/vendor.9393104e7831a4c3874e.js:11:361888)\n    at n (http://localhost:18080/static/js/vendor.9393104e7831a4c3874e.js:6:652)\n    at HTMLButtonElement.t (http://localhost:18080/static/js/vendor.9393104e7831a4c3874e.js:6:5222)'
        aar = /http(.+).js/.exec(str)
        console.log(aar)
        aar = /http(\S+).js/.exec(str)
        console.log(aar)
```

**Comment by bingoogolapple** [comment]
```JavaScript
let stackTrace = 'TypeError: Cannot read property \'length\' of undefined\n    at o.submit (\'http://localhost:18080/static/js/13.d54f45b1cc087699157a.js:1:3641)\n    at o.n [as submit] (http://localhost:18080/static/js/vendor.9393104e7831a4c3874e.js:6:664)\n    at click (http://localhost:18080/static/js/13.d54f45b1cc087699157a.js:1:5886)\n    at o.t (http://localhost:18080/static/js/vendor.9393104e7831a4c3874e.js:6:5222)\n    at o.e.$emit (http://localhost:18080/static/js/vendor.9393104e7831a4c3874e.js:6:56660)\n    at o.handleClick (http://localhost:18080/static/js/vendor.9393104e7831a4c3874e.js:11:361888)\n    at n (http://localhost:18080/static/js/vendor.9393104e7831a4c3874e.js:6:652)\n    at HTMLButtonElement.t (http://localhost:18080/static/js/vendor.9393104e7831a4c3874e.js:6:5222)'
stackTrace = 'Error: 测试出错了Promise内部\n    at http://localhost:18080/static/js/12.83909fd65985ada676db.js:1:3796'
stackTrace = 'Error: 测试出错了Promise外部\n    at o.fetchData (http://localhost:18080/static/js/9.9ce6fe26ce7ee6d96fa1.js:1:8216)\n    at o.n [as fetchData] (http://localhost:18080/static/js/vendor.9393104e7831a4c3874e.js:6:664)\n    at o.created (http://localhost:18080/static/js/9.9ce6fe26ce7ee6d96fa1.js:1:9459)\n    at he (http://localhost:18080/static/js/vendor.9393104e7831a4c3874e.js:6:8482)\n    at o.e._init (http://localhost:18080/static/js/vendor.9393104e7831a4c3874e.js:6:55376)\n    at new o (http://localhost:18080/static/js/vendor.9393104e7831a4c3874e.js:6:17005)\n    at Ee (http://localhost:18080/static/js/vendor.9393104e7831a4c3874e.js:6:12051)\n    at init (http://localhost:18080/static/js/vendor.9393104e7831a4c3874e.js:6:54592)\n    at o (http://localhost:18080/static/js/vendor.9393104e7831a4c3874e.js:6:63942)\n    at a (http://localhost:18080/static/js/vendor.9393104e7831a4c3874e.js:6:63564)'
stackTrace = 'TypeError: Cannot read property \'length\' of undefined\n    at http://localhost:18080/static/js/14.29ac438740546af8522e.js:1:12038'
let resultAar = /http(\S+).js:(\d+):(\d+)/.exec(stackTrace)
console.log(resultAar)
if (resultAar && resultAar.length === 4) {
  let mapFileUrl = 'http' + resultAar[1] + '.js.map'
  console.log('map文件路径：' + mapFileUrl)
  let lineNumber = resultAar[2]
  console.log('行号：' + lineNumber)
  let columnNumber = resultAar[3]
  console.log('列号：' + columnNumber)
} else {
  console.log('解析堆栈信息失败')
}
```
